### ISSUE TITLE
'MULTI' setting in 'serial port speed' does not persist in backup

### ISSUE THREAD

**Issue by mikeller** [openLRSng/openLRSng-configurator#42]
When setting the serial port speed for the TX module and selecting 'MULTI' (for Multiprotocol), the setting persists normally to the module.
But when backing up the profile into a file, and then restoring from the file, the serial port speed is set to '115200'.

**Comment by csurf** [comment]
@mikeller 
...just an FYI, PR #43 which might be somewhat related

**Comment by csurf** [comment]
@mikeller 
ok, this looks like it's due to the tx_console_baud patch.
Are you testing off firmware master?

**Comment by csurf** [comment]
if we upgrade the firmware to 4.0.0 and use the patched Configurator from #40, it *should* work

**Comment by csurf** [comment]
ok, I tested against firmware master with version upgraded to '4.0.0' and with Configurator w/ #40, and was able to successfully backup & restore a profile.

FYI, it wasn't just the MULTI profile by this bug. 
The entire TX config can't be saved due to being incompatible. 

I need to set the TX config into 'read-only' mode for older config versions...

**Comment by csurf** [comment]
this should be resolved by #46, and latest 3.9 firmware from repo should work / be compatible with Configurator. closing. please reopen if the problem persists...

**Comment by mikeller** [comment]
Confirmed working, thanks @csurf.
