### ISSUE TITLE
not possible to save bind data for RX

### ISSUE THREAD

**Issue by csurf** [openLRSng/openLRSng-configurator#57]
Apparently, there's currently no way to save the current `BIND_DATA` structure to the RX when connecting remotely from a TX to an RX. So, an RX isn't automatically bound to the current TX when connecting remotely from TX->RX and clicking the "save to EEPROM" button.

IOW, just because you connect remotely from a TX to an RX module, it doesn't mean that they're consequently bound to each other. I think this goes against what the expected behavior might be in many cases...

I feel that, at the very least, we should have another button (labeled "Bind Receiver" or something of this nature) that allows the user to save the current `BIND_DATA` structure from the TX to the currently-connected RX, i.e., 'bind' the RX to the TX without having to go through the process of binding via some other means.

@mikeller & others, feedback needed...

**Comment by mikeller** [comment]
I think having a 'bind' button in the configurator is a good idea. Another one would be to allow the RX to dump / restore the current bind information, so that for example an RX with a hardware problem can be replaced and config **and** bind information restored in one go, without having to bind the new RX again.

I don't think that automatically binding the RX to a TX when it is used to configure the RX is a good idea - if users own more than one TX they might just grab whatever TX they have handy (or the one with an onboard USB port) to configure their RX, not expecting the bind information to change because of this.
